### ISSUE TITLE
Error in generating data

### ISSUE THREAD

**Issue by mbchang** [ellisk42/TikZ#1]
Hi, I'm am encountering an error when I run `python makeSyntheticData.py 100000`. Could it be a dependency I am missing?

The folder `syntheticTrainingData` is created, but it is empty:
```
>>> tree syntheticTrainingData/
syntheticTrainingData/
├── 0
├── 12000
├── 15000
├── 18000
├── 21000
├── 24000
├── 27000
├── 3000
├── 30000
├── 6000
└── 9000

11 directories, 0 files
```

My terminal output is
```
>>> python makeSyntheticData.py 100000
rm: syntheticTrainingData.tar: No such file or directory
[('randomScene', 0, 1000), ('randomScene', 1000, 1000), ('randomScene', 2000, 1000), ('randomScene', 3000, 1000), ('randomScene', 4000, 1000), ('randomScene', 5000, 1000), ('randomScene', 6000, 1000), ('randomScene', 7000, 1000), ('randomScene', 8000, 1000), ('randomScene', 9000, 1000), ('randomScene', 10000, 1000), ('randomScene', 11000, 1000), ('randomScene', 12000, 1000), ('randomScene', 13000, 1000), ('randomScene', 14000, 1000), ('randomScene', 15000, 1000), ('randomScene', 16000, 1000), ('randomScene', 17000, 1000), ('randomScene', 18000, 1000), ('randomScene', 19000, 1000), ('randomScene', 20000, 1000), ('randomScene', 21000, 1000), ('randomScene', 22000, 1000), ('randomScene', 23000, 1000), ('randomScene', 24000, 1000), ('randomScene', 25000, 1000), ('randomScene', 26000, 1000), ('randomScene', 27000, 1000), ('randomScene', 28000, 1000), ('randomScene', 29000, 1000), ('randomScene', 30000, 1000), ('randomScene', 31000, 1000), ('randomScene', 32000, 1000), ('randomScene', 33000, 1000), ('randomScene', 34000, 1000), ('randomScene', 35000, 1000), ('randomScene', 36000, 1000), ('randomScene', 37000, 1000), ('randomScene', 38000, 1000), ('randomScene', 39000, 1000), ('randomScene', 40000, 1000), ('randomScene', 41000, 1000), ('randomScene', 42000, 1000), ('randomScene', 43000, 1000), ('randomScene', 44000, 1000), ('randomScene', 45000, 1000), ('randomScene', 46000, 1000), ('randomScene', 47000, 1000), ('randomScene', 48000, 1000), ('randomScene', 49000, 1000), ('randomScene', 50000, 1000), ('randomScene', 51000, 1000), ('randomScene', 52000, 1000), ('randomScene', 53000, 1000), ('randomScene', 54000, 1000), ('randomScene', 55000, 1000), ('randomScene', 56000, 1000), ('randomScene', 57000, 1000), ('randomScene', 58000, 1000), ('randomScene', 59000, 1000), ('randomScene', 60000, 1000), ('randomScene', 61000, 1000), ('randomScene', 62000, 1000), ('randomScene', 63000, 1000), ('randomScene', 64000, 1000), ('randomScene', 65000, 1000), ('randomScene', 66000, 1000), ('randomScene', 67000, 1000), ('randomScene', 68000, 1000), ('randomScene', 69000, 1000), ('randomScene', 70000, 1000), ('randomScene', 71000, 1000), ('randomScene', 72000, 1000), ('randomScene', 73000, 1000), ('randomScene', 74000, 1000), ('randomScene', 75000, 1000), ('randomScene', 76000, 1000), ('randomScene', 77000, 1000), ('randomScene', 78000, 1000), ('randomScene', 79000, 1000), ('randomScene', 80000, 1000), ('randomScene', 81000, 1000), ('randomScene', 82000, 1000), ('randomScene', 83000, 1000), ('randomScene', 84000, 1000), ('randomScene', 85000, 1000), ('randomScene', 86000, 1000), ('randomScene', 87000, 1000), ('randomScene', 88000, 1000), ('randomScene', 89000, 1000), ('randomScene', 90000, 1000), ('randomScene', 91000, 1000), ('randomScene', 92000, 1000), ('randomScene', 93000, 1000), ('randomScene', 94000, 1000), ('randomScene', 95000, 1000), ('randomScene', 96000, 1000), ('randomScene', 97000, 1000), ('randomScene', 98000, 1000), ('randomScene', 99000, 1000)]
Sampled 1000 programs.
Sampled 1000 programs.
Sampled 1000 programs.
Sampled 1000 programs.
Sampled 1000 programs.
Sampled 1000 programs.
Sampled 1000 programs.
Sampled 1000 programs.
Sampled 1000 programs.
Sampled 1000 programs.
WARNING: didn't render to zero prefixed filenames. Trying without prefixes:
ERROR: didn't get any files without zero prefixes either. Here is the latex output:
Traceback (most recent call last):
  File "makeSyntheticData.py", line 267, in <module>
    Pool(workers).map(handleGeneration, offsetsAndCounts)
  File "<user>/.anaconda2/envs/cp2/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "<user>/.anaconda2/envs/cp2/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
Exception: No image output from latex process. prefix = /var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87, len(sources) = 100, fs = 
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-0.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-1.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-2.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-3.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-4.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-5.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-6.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-7.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-8.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-9.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-10.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-11.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-12.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-13.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-14.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-15.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-16.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-17.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-18.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-19.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-20.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-21.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-22.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-23.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-24.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-25.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-26.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-27.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-28.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-29.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-30.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-31.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-32.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-33.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-34.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-35.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-36.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-37.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-38.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-39.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-40.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-41.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-42.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-43.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-44.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-45.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-46.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-47.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-48.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-49.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-50.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-51.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-52.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-53.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-54.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-55.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-56.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-57.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-58.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-59.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-60.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-61.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-62.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-63.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-64.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-65.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-66.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-67.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-68.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-69.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-70.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-71.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-72.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-73.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-74.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-75.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-76.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-77.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-78.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-79.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-80.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-81.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-82.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-83.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-84.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-85.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-86.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-87.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-88.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-89.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-90.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-91.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-92.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-93.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-94.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-95.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-96.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-97.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-98.png
/var/folders/kp/lxd_r10n2kq6y69554053mm00000gn/T/tmpURoZ87-99.png
,checks = 
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
```

**Comment by jakubLangr** [comment]
:+1: exact same issue.

Any progress on this? Did you resolve this @mbchang? 

I do find a bit odd that it is still using python2.

**Comment by mhsung** [comment]
I could solve the problem by installing latest texlive:
sudo add-apt-repository ppa:jonathonf/texlive
sudo apt-get install texlive-latex-base
sudo apt-get install texlive-latex-extra

You can see the pdflatex error message by changing line42 in 'render.py' to this:
os.system("cd /tmp; echo X|pdflatex -shell-escape %s" % temporaryName)
