### ISSUE TITLE
Cannot launch the program

### ISSUE THREAD

**Issue by Enigma-li** [ellisk42/TikZ#4]
Hi,

I tried the released docker, but I cannot run the demo code: python demo.py 29.

The error outputs are:
root@fad1981a086d:/app/TikZ# python demo.py 29   
Traceback (most recent call last):
  File "demo.py", line 9, in <module> import argparse 
  File "/usr/local/lib/python2.7/argparse.py", line 86, in <module> import copy as _copy  
  File "/usr/local/lib/python2.7/copy.py", line 52, in <module>  import weakref  
  File "/usr/local/lib/python2.7/weakref.py", line 14, in <module> from _weakref import (      
ImportError: cannot import name _remove_dead_weakref

How to solve this?

**Comment by Enigma-li** [comment]
Updating Python 2.7.13 to 2.7.18 solves the problem!
